import { Rajdhani } from "next/font/google";
import "./globals.css";
import Header from "@/Header/page";
import Footer from "@/Footer/page";

const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export const metadata = {
  title: "Deshi Gajor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${rajdhani.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
